// Mocks generated by Mockito 5.0.16 from annotations
// in favorites_movies/test/features/popular_movies/data/repositories/movie_details_repository_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:favorites_movies/features/movies/data/datasources/movie_details_remote_data_source.dart'
    as _i3;
import 'package:favorites_movies/features/movies/data/models/detail_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeDetailModel_0 extends _i1.Fake implements _i2.DetailModel {}

/// A class which mocks [MovieDetailsRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieDetailsRemoteDataSource extends _i1.Mock
    implements _i3.MovieDetailsRemoteDataSource {
  MockMovieDetailsRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.DetailModel> getMovieDetails({int? id}) =>
      (super.noSuchMethod(Invocation.method(#getMovieDetails, [], {#id: id}),
              returnValue: Future<_i2.DetailModel>.value(_FakeDetailModel_0()))
          as _i4.Future<_i2.DetailModel>);
  @override
  String toString() => super.toString();
}
