// Mocks generated by Mockito 5.0.16 from annotations
// in favorites_movies/test/features/popular_movies/data/repositories/search_movies_repository_impl.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:favorites_movies/features/movies/data/datasources/search_movies_remote_data_source.dart'
    as _i2;
import 'package:favorites_movies/features/movies/data/models/movie_model.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [SearchMoviesRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchMoviesRemoteDataSource extends _i1.Mock
    implements _i2.SearchMoviesRemoteDataSource {
  MockSearchMoviesRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.MovieModel>> searchMovies(String? title) =>
      (super.noSuchMethod(Invocation.method(#searchMovies, [title]),
              returnValue:
                  Future<List<_i4.MovieModel>>.value(<_i4.MovieModel>[]))
          as _i3.Future<List<_i4.MovieModel>>);
}
