// Mocks generated by Mockito 5.0.16 from annotations
// in favorites_movies/test/features/popular_movies/domain/usecases/search_movies_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:favorites_movies/features/movies/domain/entities/movie.dart'
    as _i4;
import 'package:favorites_movies/features/movies/domain/repositories/search_movies_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [SearchMoviesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchMoviesRepository extends _i1.Mock
    implements _i2.SearchMoviesRepository {
  MockSearchMoviesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Movie>> searchMovies({String? title}) =>
      (super.noSuchMethod(Invocation.method(#searchMovies, [], {#title: title}),
              returnValue: Future<List<_i4.Movie>>.value(<_i4.Movie>[]))
          as _i3.Future<List<_i4.Movie>>);
}
